Add Multipacks documentation
phomc/docs pull request #1
Opened 2023-01-26 13:40 UTC by nahkd123

Need someone to ensure spelling and grammar is correct.

2023-01-27 09:22 UTC, anhcraft requested changes

2023-01-27 09:22 UTC, anhcraft commented on docs/multipacks/getting-started/02-your-first-pack.md
> +  + You can use any plain text editor that can edits ``.txt`` files, such as Windows Notepad, ``vim`` or Visual Studio Code. Rich text editors like WordPad might not works with Multipacks.
can edit

2023-01-27 09:22 UTC, anhcraft commented on docs/multipacks/intro.md
> +
also here

2023-01-27 09:22 UTC, anhcraft commented on docs/multipacks/modifiers/atlases.md
> +
will create

2023-01-29 07:46 UTC, anhcraft approved these changes

2023-01-29 07:46 UTC, JustMangoT approved these changes

2023-01-29 07:49 UTC, merged